# Generated by Django 4.0.7 on 2022-11-25 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_first_name_patient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('stock', models.IntegerField(default=0)),
                ('date_added', models.DateField(default=datetime.date(2022, 11, 25))),
                ('item_price', models.IntegerField()),
                ('item_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 10, 2, 32, 830807)),
        ),
    ]
