# Generated by Django 4.0.7 on 2022-11-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_patient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventory',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
