# Generated by Django 4.0.7 on 2022-11-25 09:12

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_iteminventory_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=35)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('join_date', models.DateField(default=datetime.date(2022, 11, 25))),
            ],
        ),
    ]
