# Generated by Django 4.0.7 on 2022-11-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_staffinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinventory',
            name='profile',
            field=models.ImageField(upload_to='staff'),
        ),
    ]
