# Generated by Django 4.0.7 on 2022-11-29 15:37

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_iteminventory_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminventory',
            name='date_added',
            field=models.DateField(default=datetime.date(2022, 11, 29)),
        ),
        migrations.AlterField(
            model_name='staffinventory',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NG'),
        ),
        migrations.AlterField(
            model_name='staffinventory',
            name='join_date',
            field=models.DateField(default=datetime.date(2022, 11, 29)),
        ),
    ]
