# Generated by Django 4.0.7 on 2022-12-17 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_iteminventory_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventory',
            name='image',
            field=models.ImageField(default=None, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='iteminventory',
            name='date_added',
            field=models.DateField(default=datetime.date(2022, 12, 17)),
        ),
        migrations.AlterField(
            model_name='staffinventory',
            name='join_date',
            field=models.DateField(default=datetime.date(2022, 12, 17)),
        ),
        migrations.AlterField(
            model_name='staffinventory',
            name='profile',
            field=models.ImageField(default=None, upload_to='staff'),
        ),
    ]
